base/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

'''
from message.views import home_view #, RecipesView, RecipesAdvancedView, ProfileView

from Recipes.views import TopView, register_view, login_view, template_view, addcomment_view
from Recipes.views import dodajrecept_view, dodajpostopek_view, dodajsestavina_view, addrating_view
from Recipes.views import menjajgeslo_view, menjajime_view
from Recipes.models import Vrste,Postopki,Ocene,Sestavine,Slike,Komentarji,Recepti,ReceptiSestavine
'''

# from CustomUser.models import CustomUser

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('message.urls')),
]

urlpatterns += staticfiles_urlpatterns()

message/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from .views import home_view, register_view, login_view, group_chat_view, users_view, ProfileView, MessageListView, \
    MessageCreateView

# ViewSets define the view behavior.


app_name = 'message'

urlpatterns = [
    path("", home_view, name="home"),

    path("login/", login_view, name="login"),
    path("logout", auth_views.LogoutView.as_view(next_page='/'), name="logout"),

    path("register/", register_view, name="register"),
    path('users/', users_view, name="users"),

    # Classic calls
    path('profile/<int:pk>', ProfileView.as_view(), name="profile"),

    path('groupchat/', group_chat_view, name="groupchat"),
    path('private_message/<int:receiving_user__id>', group_chat_view, name="private_message"),

    # REST calls
    path('list/', MessageListView.as_view(), name='list'),
    path('list/<int:pk>', MessageListView.as_view(), name='list_private'),
    path('create/', csrf_exempt(MessageCreateView.as_view()), name='create'),
    path('create/<int:pk>', csrf_exempt(MessageCreateView.as_view()), name='create_private'),
]

message/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models


class Message(models.Model):
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    receiver = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True,
                                 related_name='my_private_messages')
    txt = models.TextField(max_length=512)
    datum = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['datum']

    def __str__(self):
        return self.txt

message/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Message


class SubmissionForm(forms.ModelForm):
    txt = forms.CharField(widget=forms.Textarea(attrs={'class': 'submission__message'}))

    class Meta:
        model = Message
        fields = ('txt',)


class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name']

message/views.py
from django.contrib.auth import login, authenticate, logout, get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import TemplateView, ListView
from django.views.generic.edit import ModelFormMixin, UpdateView
from rest_framework.generics import ListAPIView, CreateAPIView

from .forms import SubmissionForm, ProfileForm
from .models import Message
# Create your views here.
# Registracija, login (logout je pod template)
from .serializers import MessageSerializer


def home_view(request, *args):
    return render(request, "about.html")


def register_view(request):
    # if request.user.is_authenticated:
    # return redirect('djangobin:profile', username=request.user.username)

    if request.method == 'POST':
        f = UserCreationForm(request.POST)
        if f.is_valid():
            f.save()
            return redirect("/")

    else:
        f = UserCreationForm()

    return render(request, 'register.html', {'form': f})


def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, user)
            return redirect("/")
    else:
        form = AuthenticationForm()
    return render(request, "login.html", {"form": form})

    return render(request, "login.html")


def logout_view(request):
    return logout(request)


class ChatView(ModelFormMixin, ListView):
    template_name = 'groupchat.html'
    model = Message
    form_class = SubmissionForm

    def get_queryset(self):
        qs = Message.objects.filter(receiver__isnull=True)
        other_user = self.kwargs.get('other_user')

        if other_user:
            qs = Message.objects.filter(receiver=other_user)

        return qs


def group_chat_view(request, *context, **kwargs):
    qs = Message.objects.filter(receiver__isnull=True)
    other_user = None
    other_user_id = kwargs.get('receiving_user__id')
    form = SubmissionForm(request.POST)
    print(other_user_id)
    context = {}

    if other_user_id:
        other_user = get_object_or_404(get_user_model(), pk=other_user_id)
        qs = Message.objects.filter(
            Q(receiver=other_user, sender=request.user) | Q(receiver=request.user, sender=other_user)
        )
        context['other_user_id'] = other_user_id

    if request.method == 'POST':
        if form.is_valid():
            message = form.save(commit=False)
            message.sender = request.user
            if other_user:
                message.receiver = other_user
            message.save()
            form = SubmissionForm()
            return HttpResponseRedirect(request.path_info)

    context['form'] = form
    context['qs'] = qs
    context['kwargs'] = kwargs
    return render(request, "groupchat.html", context)


def users_view(request):
    Users = get_user_model()
    users = Users.objects.all()
    args = {"users": users}
    return render(request, "users.html", args)


class UserMessageView(TemplateView):
    template_name = 'groupchat.html'


def user_view(request):
    userId = request.kw
    data = User.objects.get(id=userId)
    # comm = Komentarji.objects.all().filter(recept_id=recipeId)
    # info = ReceptiSestavine.objects.all().filter(recept_id=recipeId)
    # face = Postopki.objects.all().filter(recept_id=recipeId)
    # rate = Ocene.objects.all().filter(recept_id=recipeId)

    # args = {"data": data, "comm": comm, "face": face, "info": info,"rate": rate}
    # return render(request, "dodajrecept.html", args)

    # return render(request, "recept.html", args)

    return render(request, "user.html", data)


class ProfileView(UpdateView):
    template_name = "profile.html"
    model = get_user_model()
    form_class = ProfileForm

    def get_success_url(self):
        return reverse('message:profile', kwargs={'pk': self.kwargs['pk']})


def profile_view(request):
    return render(request, "profile.html")


class MessageListView(ListAPIView):
    serializer_class = MessageSerializer

    def get_queryset(self):
        pk = self.kwargs.get('pk')
        qs = Message.objects.filter(receiver__isnull=True)
        u = self.request.user

        if pk:
            other_user = get_object_or_404(get_user_model(), pk=pk)
            qs = Message.objects.filter(
                Q(receiver=other_user, sender=u) | Q(receiver=u, sender=other_user)
            )

        return qs


class MessageCreateView(CreateAPIView):
    queryset = Message.objects.all()
    serializer_class = MessageSerializer

message/templates/about.html
{% extends "base.html" %}

{% block content %}

    Spletna stran, katero smo naredili in poimenovali ChatApp je narejena s popularno pythonovo knjižnjico Django,
    katera med drugim omogoča lahko povezavo z podatkovno bazo PostGreSQL.

    <p class="about">ChatApp je zgrajen iz osnovne strani, imenovane template.html, katera vsebuje navbar.html in blok
        element, v katerega insertiramo druge strani v uporabi. Najpomembnejši od teh sta skupinski pogovor
        (groupchat.html), ki omogoča pogovor med vsemi registriranimi uporabniki in uporabniki (users.html), ki omogoča
        privatni pogovor z izbranim uporabnikom. Na strani se najdejo tudi strani za prijavo in registracijo, domača
        stran, ki vsebuje ta opis strani ter profil, ki vsebuje le prazno stran. </p>

{% endblock %}

message/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <link rel="stylesheet" href="{% static '/style.css' %}"/>
    <title>Chat App</title>
    {% block head %}{% endblock %}
</head>
<body>
<div class="content">
    {% include "navbar.html" %}

    {% block content %}{% endblock %}
</div>
</body>
</html>

message/templates/groupchat.html
{% extends "base.html" %}
{% load static %}
{% block head %}
    <script src="{% static 'vue.min.js' %}"></script>
{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <div class="messages" id="chatbox">
            <div class="message" v-for="m in messages"
                 :class="{
                    'message--mine': myId == m.sender,
                    'message--other': myId != m.sender,
                 }">
                <p class="username" v-html="m.username"></p>
                <p class="userdate" v-html="m.datum"></p>
                <p class="txt" v-html="m.txt"></p>
            </div>

            <div class="submission">
                <form method="POST" @submit.prevent="handleSubmit">
                    <textarea v-model="newTxt" rows="10" class="submission__textarea"
                              name="{{ form.txt.html_name }}"></textarea>

                    <button class="submission__button" type="submit">Dodaj</button>
                </form>
            </div>
        </div>



    {% else %}
        <p>Niste prijavljeni</p>
        <a href="{% url 'message:login' %}">login</a>
    {% endif %}

    <script lang="text/javascript">
        window.addEventListener('DOMContentLoaded', () => {
            var app = new Vue({
                el: '#chatbox',
                data: {
                    messages: [],
                    myUsername: '{{ request.user.username }}',
                    myId: {{ request.user.pk }},
                    otherId: {% if other_user_id %}{{ other_user_id }}{% else %}null{% endif %},
                    urls: {
                        list: "{% if other_user_id %}{% url 'message:list_private' pk=other_user_id %}{% else %}{% url 'message:list' %}{% endif %}",
                        create: "{% if other_user_id %}{% url 'message:create_private' pk=other_user_id %}{% else %}{% url 'message:create' %}{% endif %}",
                    },
                    newTxt: '',
                    csrfToken: "{{ csrf_token }}"
                },
                mounted() {
                    this.getMessages()
                    setInterval(this.getMessages, 500)
                },
                methods: {
                    async getMessages() {
                        var response = await fetch(this.urls.list)
                        this.messages = await response.json()
                    },
                    async createMessage() {
                        var vals = {
                            sender: this.myId,
                            txt: this.newTxt,
                            receiver: this.otherId,
                        }
                        var response = await fetch(
                            this.urls.create,
                            {
                                method: 'POST',
                                body: JSON.stringify(vals),
                                headers: {
                                    'Content-Type': 'application/json',
                                    'X-CSRFToken': this.csrfToken,
                                },
                                mode: 'same-origin'
                            }
                        )
                        if (response.ok) {
                            this.newTxt = ''
                        }
                    },
                    handleSubmit(e) {
                        this.createMessage()
                    }
                },
            })
        })
    </script>

{% endblock %}

message/templates/login.html
{% extends "base.html" %}

{% block content %}
    <div class="login">
        <h4>Login</h4>

        <form method="POST">
            {% csrf_token %}
            <p class="login__username">Uporabniško ime: {{ form.username }}</p>
            <p class="login__password">Geslo: {{ form.password }}</p>
            <a href="{% url 'message:login' %}">
                <button type="submit">Login</button>
            </a>
        </form>
    </div>
{% endblock %}

message/templates/navbar.html
{% load static %}

<nav>
    <ul id="navbar" class="navbar__list">
        <li class="page__title"><a id="home" href="/">
            <img class="page__title__image" src="{% static 'images/Logo.png' %}" alt="Logo" width="250"/></a>
        </li>
        <li class="navbar__list__item">
            <a href="/">Domov</a>
        </li>
        <li class="navbar__list__item">
            <a href="/users/">Uporabniki</a>
        </li>
        <li class="navbar__list__item">
            <a href="/groupchat/">Skupinski chat</a>
        </li>
        <li class="navbar__list__item">
            <a href="/login/">Prijava</a>
        </li>
        {% if request.user.is_authenticated %}
            <li class="navbar__list__item">
                <a href="{% url 'message:profile' pk=request.user.pk %}">Profil</a>
            </li>
        {% else %}
            <li class="navbar__list__item">
                <a href="{% url 'message:register' %}">Registracija</a>
            </li>
        {% endif %}
        <li class="navbar__list__user">
            {% if user.is_authenticated %}
                Dober dan {{ user }}!
                <p><a href="{% url 'message:logout' %}">Odjava</a></p>
            {% else %}
                <p>Prosim prijavi se</p>
                <a href="{% url 'message:login' %}">Prijava</a>
            {% endif %}</li>
    </ul>
</nav>

message/templates/profile.html
{% extends "base.html" %}

{% block content %}

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Pošlji</button>
    </form>

{% endblock %}

message/templates/register.html
{% extends "base.html" %}

{% block content %}
    <div class="register">
        <h4>Registracija</h4>

        <form method="post">

            {% csrf_token %}
            Uporabniško ime: {{ form.username }} <br>
            <ul class="register__demands">
                <li class="register__demands__item"> Maksimalno 150 znakov</li>
                <li class="register__demands__item"> Dovoljene le črke, številke in @, ., +, -, _</li>
            </ul>
            Geslo: {{ form.password1 }} <br>
            <ul clas="register__demands">
                <li class="register__demands__item"> Geslo ne sme biti prepodobno ostalim osebnim podatkom</li>
                <li class="register__demands__item"> Geslo mora imeti vsaj 8 znakov</li>
                <li class="register__demands__item"> Geslo ne sme biti prepopularno (npr. 123456 ali password)</li>
                <li class="register__demands__item"> Geslo ne sme biti le iz številk</li>
            </ul>
            Potrditev gesla: {{ form.password2 }} <br>

            <input type="hidden" name="next" value="{{ next }}">
            <a href="{% url 'message:logout' %}">
                <button type="submit" class="register__submit">Submit</button>
            </a>

        </form>
    </div>
{% endblock %}

message/templates/users.html
{% extends "base.html" %}

{% block content %}

    Trenutno registrirani uporabniki (pritisni na uporabnika za privatno komunikacijo): <br>
    {% if request.user.is_authenticated %}
        {% for u in users %}
            {% comment %} <p class="username"><a href="/lookup?id={{ u.username }}"> {{u.username}} </a></p> {% endcomment %}
            <p class="username">
                <a href="{% url 'message:private_message' receiving_user__id=u.pk %}">
                    {{ u.username }}
                </a>
            </p>

        {% endfor %}
    {% else %}
        <p>Niste prijavljeni</p>
        <a href="{% url 'message:login' %}">login</a>
    {% endif %}

{% endblock %}